
# Server
server.port=80
debug=false
server.address=0.0.0.0
java.net.preferIPv4Stack=true
server.tomcat.connection-timeout=600000
spring.mvc.async.request-timeout=600000

#.env
spring.config.import=optional:classpath:application-local.properties

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/truck_optimization
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

# MongoDB
spring.data.mongodb.uri=${MONGO_URI:}
spring.data.mongodb.auto-index-creation=true

#API
ors.api.key=${ORS_API_KEY:}
ors.api.timeout-seconds=20
geomaps.api.key=${GEOMAPS_API_KEY:}


# Routing Configuration
# Remove this crap
routing.number-of-trucks=10
routing.truck-capacity=10
routing.max-distance-miles=1000
routing.optimal-distance-miles=400
routing.calculation-time=120
routing.penalty-per-mile-over=50
routing.penalty-per-mile-under=50
routing.cost-of-adding-truck=100000
# Time-based routing (in seconds)
routing.depot-start-time-seconds=0
routing.depot-end-time-seconds=86400
routing.max-route-duration-seconds=43200


logging.file.path=logs/
logging.file.name=logs/application.log
logging.level.root=INFO
logging.level.org.springframework.web=INFO

# Simple local login credentials
app.security.username=admin
app.security.password=admin123
